added lucky run function

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,15 +1,9 @@
 #!/usr/bin/env bash
-# name: install scipt for dockerized NTNX RestAPI dev env
-# author: jason lindemuth
-# v1.0
-# download the wrapper script with the command:
-# wget -O install https://github.com/periplume/ntnx-api/raw/master/install && chmod 755 install
-# or
-# curl -OL https://github.com/periplume/ntnx-api/raw/master/install && chmod 755 install
-# NOTE: the above is unreliable if file was recently committed
-#
-# debug with set -x
-
+# desc: install/run scipt for dockerized NTNX RestAPI dev env
+# author: Jason Lindemuth
+# source: https://github.com/periplume/ntnx-api
+# version 1.0
+#set -x
 scriptname=${0##*/}
 logfile=$scriptname.log
 rawgit=https://github.com/periplume/ntnx-api/raw/master
@@ -23,7 +17,19 @@ debug=1
 # tools we need in this script
 commands="date wget curl git docker diff"
 
+usage () {
+	cat << EOF
+usage: $scriptname
+$ $scriptname $BLUE check $RESET      (test the environment and identify missing tools)
+$ $scriptname $BLUE updateself $RESET (fetch the latest version of this script)
+$ $scriptname $BLUE build $RESET      (build the docker image)
+$ $scriptname $BLUE run $RESET        (run the container and attach to the shell)
+EOF
+exit
+}
+
 spinner () {
+	# fancy whirligig to indicate we're waiting on a long running task
 	# care of http://fitnr.com/showing-a-bash-spinner.html
 	local pid=$1
 	local delay=0.75
@@ -58,8 +64,7 @@ isOnline () {
 	# args: none
 	# success: return 0 if online
 	# failure: return 1 if offline
-	# requires wget or curl, prefers wget
-	# TODO: assumes google.com = online: what about dark sites?
+	# TODO: assumes google.com = online; this should be improved
 	if [ $wget_exists = 0 ]
 	then
 		wget -q --spider http://www.google.com
@@ -81,7 +86,7 @@ isOnline () {
 }
 
 isScriptCurrent () {
-	# desc: is this script itself current to remote git master branch
+	# desc: compare this script to the git master version
 	# args: none
 	# success: return 0 if files are same
 	# failure: return 1 if files are different
@@ -121,8 +126,9 @@ timestamp () {
 }
 
 logevent () {
+	# desc: logging facility
   # $@: one arg (multi word) the log message
-  # logs event to global logfile if debug=1
+  # logs event to global $logfile if debug=1
 	if [ $debug = 0 ]
 	then
 		return 0
@@ -132,87 +138,239 @@ logevent () {
 	fi
 }
 
-# attempt to colorize the output if tput exists
-# TODO: make this a function and a bit smarter
-if [ -x "$(command -v tput)" ]
-then
-	logevent "f:$FUNCNAME: true[0]: tput exists and is executable, setting colors"
-	GREEN="$(tput setaf 2)"
-	YELLOW="$(tput setaf 3)"
-	RED="$(tput setaf 1)"
-	RESET="$(tput setaf 15)"
-	#RESET="$(tput setaf 7)"  # check for tput colors = 8 | 256
-fi
-
-# main
-# checking for the things we need to make this work
-# check for commands and set var as $cmd_exists = 0/1 (true/false)
-# TODO: make some of the below functions
-for CMD in $commands
-do
-	var_name=${CMD}_exists
-	checkCommand $CMD
-	if [ $? = 0 ]
+colorize () {
+	# desc: rudimentary term inquiry to set output colorization
+	# args: none
+	if [ -x "$(command -v tput)" ]
+	then
+		logevent "f:$FUNCNAME: true[0]: tput exists and is executable, setting colors"
+		if [ $(tput colors) = 256 ]
 		then
-		eval ${var_name}='0'
-	else
-		eval ${var_name}='1'
+			logevent "f:$FUNCNAME: true[0]: tput reports 256 colors; setting color VAR tags"
+			GREEN="$(tput setaf 2)"
+			YELLOW="$(tput setaf 3)"
+			RED="$(tput setaf 1)"
+			BLUE="$(tput setaf 4)"
+			RESET="$(tput setaf 15)"
+		elif [ $(tput colors) = 8 ]
+		then
+			logevent "f:$FUNCNAME: true[0]: tput reports 8 colors; setting color VAR tags"
+			GREEN="$(tput setaf 2)"
+			YELLOW="$(tput setaf 3)"
+			RED="$(tput setaf 1)"
+			BLUE="$(tput setaf 4)"
+			RESET="$(tput setaf 8)"
+		else
+			logevent "f:$FUNCNAME: err[1]: tput colors reports number other than 8 or 256"
+		fi
 	fi
-	if [ ${!var_name} = 0 ]
+}
+
+checkEnv () {
+	# desc: run tests to determine if we can run here
+	# args: none
+	# return 0 if PASS
+	# return 1 if FAIL
+	for CMD in $commands
+	do
+		var_name=${CMD}_exists
+		checkCommand $CMD
+		if [ $? = 0 ]
+			then
+			eval ${var_name}='0'
+		else
+			eval ${var_name}='1'
+		fi
+		if [ ${!var_name} = 0 ]
+		then
+			echo "[$GREEN ${!var_name} $RESET] $CMD exists"
+		# funky business to handle "need to have" vs "nice to have"
+		elif [ "$var_name" = "git_exists" ]
+		then
+			echo "[$YELLOW ${!var_name} $RESET] $CMD missing, will use wget|curl instead"
+		else
+			if [ "$var_name" = "wget_exists" ]
+			then
+				checkCommand curl
+				if [ $? = 0 ]
+				then
+					echo "[$YELLOW ${!var_name} $RESET] $CMD missing, will use curl instead"
+				else
+					echo "[$RED ${!var_name} $RESET] $CMD missing: please install $CMD"
+					CHECKOK=1
+				fi
+			else
+				echo "[$RED ${!var_name} $RESET] $CMD missing: please install $CMD"
+				CHECKOK=1
+			fi
+		fi
+	done
+	if [ -z $CHECKOK ]
 	then
-		echo "[$GREEN ${!var_name} $RESET] $CMD exists"
+		echo "$GREEN PASS $RESET command line tools test passed"
+		isOnline
+		if [ $? = 0 ]
+		then
+			ONLINE=0
+			echo "[$GREEN $? $RESET] ONLINE mode is true"
+			isScriptCurrent
+			if [ $? = 0 ]
+			then
+				echo "[$GREEN $? $RESET] script appears to be latest"
+			else
+				echo "[$YELLOW $? $RESET] script $YELLOW differs $RESET from git master"
+			fi
+		else
+			ONLINE=1
+			echo "[$YELLOW $ONLINE $RESET] ONLINE mode is false"
+			echo "[$YELLOW 1 $RESET] WARN: cannot test if script is current"
+		fi
+		return 0
 	else
-		echo "[$RED ${!var_name} $RESET] $CMD missing: please install $CMD"
-		CHECKOK=1
+		echo "$RED FAIL $RESET command line tools test failed; install missing tools"
+		return 1
 	fi
-done
+}
 
-if [ $wget_exists = 0 ] || [ $curl_exists = 0 ]
-then
-	CHECKOK=0
-fi
-if [ -n "$CHECKOK" ]
-then
-	echo "$RED FAIL $RESET prereqs not met, fix to proceed"
-	exit 1
-else
-	echo "$GREEN PASS $RESET command line tools tests passed"
-fi
-
-# check if we are online or not
-if [ $wget_exists = 0 ] || [ $curl_exists = 0 ]
-then
-	isOnline
+fetchFiles () {
+	# desc: fetch the suite of files to support the app
+	# args: none
+	# TODO: fix this function...WAY too dangerous, and broken
+	# MAKE SURE NOT TO OVERWRITE EXISTING FILES!!!
+	files="Dockerfile README.md ntnx-api.splash"
+	whichFetch
 	if [ $? = 0 ]
 	then
-		ONLINE=0
-		echo "[$GREEN $ONLINE $RESET] ONLINE mode is true"
+		fetchpre="wget -q "
+	elif [ $? = 1 ]
+	then
+		fetchpre="curl -OL "
 	else
-		ONLINE=1
-		echo "[$RED $ONLINE $RESET] ONLINE mode is false"
+		return 1
 	fi
+	for file in $files
+	do
+		eval $fetchpre $rawgit/$file
+	done
+}
+
+whichFetch () {
+	# desc: return preferred http file transfer tool
+	# args: none
+	# return 0 for wget
+	# return 1 for curl
+	# return 2 for none found
+	checkCommand wget
+	if [ $? = 0 ]
+	then
+		return 0
+	elif checkCommand curl
+	then
+		if [ $? = 0 ]
+		then
+			return 1
+		else
+			return 2
+		fi
+	fi
+}
+
+buildImage () {
+	# desc: build the docker image
+	# args: none
+	# return 0 if success
+	# return 1 if build reports error
+	echo "[$GREEN $? $RESET] building docker image...may take some time; (tail -f dockerbuild.log)"
+	(docker build --tag=periplume/ntnx-api:v1 . > dockerbuild.log 2>&1) &
+	spinner $!
+	echo "[$GREEN $? $RESET] success: run 'install run' next"
+}
+
+run () {
+	# run and attach to the container
+	echo "$GREEN PASS $RESET all tests passed...launching container now"
+	# use printf and say launching in 3...2...1...
+	sleep 3
+	clear
+	docker run -v data:/nutanix/data -it periplume/ntnx-api:v1
+}
+
+#
+# MAIN
+#
+# test for term colors and set color VARS accordingly
+colorize
+
+# read the command arguments
+if [ $# -eq 0 ];
+then
+  usage
 else
-	echo "$RED ERROR: $RESET install wget or curl to continue"
-	exit 1
+  while [ $# -gt 0 ]
+  do
+    case "$1" in
+      check)
+        if [ $# -gt 1 ]
+				then
+					usage
+        else
+					echo "TESTING environment for required tools and conditions..."
+					checkEnv
+					if [ $? = 0 ]
+					then
+						echo "$GREEN PASS $RESET run 'install build' next"
+						exit 
+					else
+						echo "$RED FAIL $RESET please install the missing tools"
+						exit
+					fi
+				fi
+        ;;
+			fetchfiles)
+				if [ $# -gt 1 ]
+				then
+					usage
+				else
+					echo "DO fetch and replace"
+					fetchFiles
+					if [ $? = 0 ]
+					then
+						echo "$GREEN OK $RESET fetched files"
+					else
+						echo "$RED FAIL $RESET failed to fetch files"
+					fi
+					shift
+				fi
+				;;
+			build)
+        if [ $# -gt 1 ]
+				then
+					echo "ERROR: build takes no arguments"
+					usage
+        else
+					buildImage
+				fi
+				shift
+				;;
+			lucky)
+				if [ $# -gt 1 ]
+				then
+					usage
+				else
+					checkEnv
+					fetchFiles
+					buildImage
+					run
+				fi
+				shift
+				;;
+			*)
+				usage
+		esac
+	done
 fi
 
-# check for newer script (if ONLINE=0)
-# fetch the latest studio package
-if [ $wget_exists = 0 ] || [ $curl_exists = 0 ] && [ $ONLINE = 0 ]
-then
-	isScriptCurrent
-	if [ ! $? = 0 ]
-	then
-		echo "[$YELLOW $? $RESET] warn: $scriptname appears to differ from git master"
-		SCRIPT_CURRENT=1
-	else
-		SCRIPT_CURRENT=0
-		echo "[$GREEN $? $RESET] $scriptname is current"
-	fi
-elif [ $ONLINE = 1 ]
-then
-	echo "[$YELLOW $ONLINE $RESET] cannot check for latest $scriptname; offline"
-fi
+exit
 
 # fetch source
 # TODO: add logic to test for existing git clone
